### ISSUE TITLE
[IDEA] Use Modern Fortran

### ISSUE THREAD

**Issue by kookma** [LLNL/H2OI95#1]
Is there any reason to use the old Fortran for implementing this new version? What do you think if we convert i to modern Fortran in modular form to be used by other programs or extensible.

**Comment by twolery** [comment]
"Old Fortran"? Wow! I could tell stories. There is no strong reason not to do what I think you are proposing (create a formal module, with potentially other changes). The usefulness would depend on the application. I'm mainly interested in the thermochemical properties, along with Debye-Huckel parameters (which are also used in thermochemical calculations). From my perspective, H2OI95, in addition to being a stand-alone code, will be the basis of a module (informal sense), when I replace the main program with a subroutine (maybe two) to interface with a certain legacy code that is used to develop thermochemical databases for use by other codes, which in turn do simulation and analysis calculations. I haven't used TYPE or CLASS constructs in H2OI95, as I didn't see them naturally adding much value. There was no effort to parallelize anything due to my intended usage, though it might be valuable for other usages. If you want to do something along those lines, that is fine, but you should be aware that in process simulation, most folks use the 97 Industrial Formulation, which is a model fit to the 95 General and Scientific Model. They do that to avoid iteration for T and P as primary variables. I am not sure that today the iteration should be such a deal killer. For me, the model-fit to-a-model thing results in a loss of accuracy (for thermochemical usage) that I prefer not to accept. You are welcome to do what you like within the limits of the open source license. Be aware, however, that I want to maintain my own main branch on GitHub, at least for the foreseeable future.

________________________________

**Comment by kookma** [comment]
@twolery Thank you for clarification!
I will fork to modify for my need!
